Controllers/CompraController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    [Authorize]
    public class CompraController : Controller
    {
        private ULSAVentasDataContext db
        {
            get
            {
                return ContextoEstatico.db;
            }
        }

        // GET: Compra
        public ActionResult Index(int idPublicacion)
        {
            Publicacion p = null;
            Usuario u = null;

            try
            {
                u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);

                List<Direccion> direcciones = db.Direccion.Where(d => d.idPersona == u.Persona.idPersona).ToList();
                List<TarjetaDeCredito> tarjetas = db.TarjetaDeCredito.Where(t => t.idPersona == u.Persona.idPersona).ToList();

                TempData["compraDireccionesUsuario"] = direcciones;
                TempData["compraTarjetasUsuario"] = tarjetas;

            }
            catch (Exception)
            {
                return Redirect(Request.UrlReferrer.ToString());
            }

            return View(p);
        }

        [HttpPost]
        public ActionResult Comprar(int idPublicacion, int cantidad, int idTarjeta, int idDireccion)
        {
            Publicacion p = null;
            TarjetaDeCredito t = null;
            Direccion d = null;
            Usuario u = null;

            Compra c = null;

            try
            {
                u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);
                t = db.TarjetaDeCredito.First(t1 => t1.idTarjeta == idTarjeta);
                d = db.Direccion.First(d1 => d1.idDireccion == idDireccion);

                c = new Compra();

                c.cantidad = cantidad;
                c.fecha = DateTime.Now;
                c.idDireccion = d.idDireccion;
                c.idPublicacion = p.idPublicacion;
                c.idTarjeta = t.idTarjeta;
                c.idUsuario = u.idUsuario;

                p.cantidad -= cantidad;

                db.Compra.InsertOnSubmit(c);
                db.SubmitChanges();

                TempData["compraCompraRealizada"] = true;
            }
            catch (Exception)
            {
                TempData["compraCompraRealizada"] = false;
                return Redirect(Request.UrlReferrer.ToString());
            }

            return RedirectToAction("Compras", "Cuenta");
        }

        [HttpGet]
        public ActionResult VerDetalle(int idCompra)
        {
            Compra c = null;

            try
            {
                c = db.Compra.First(c1 => c1.idCompra == idCompra);
            }
            catch (Exception)
            {
                return RedirectToAction("Compras", "Cuenta");
            }

            return View(c);
        }

        [HttpPost]
        public ActionResult VerDetalle(int idCompra, bool? calificacionDeCompra, string comentarioDeCompra, bool? calificacionDeVenta, string comentarioDeVenta)
        {
            Compra c = null;

            try
            {
                c = db.Compra.First(c1 => c1.idCompra == idCompra);

                c.calificacionDeCompra = calificacionDeCompra;
                c.calificacionDeVenta = calificacionDeVenta;
                c.comentarioDeCompra = comentarioDeCompra;
                c.comentarioDeVenta = comentarioDeVenta;

                db.SubmitChanges();

                TempData["compraCompraActualizada"] = true;
            }
            catch (Exception)
            {
                TempData["compraCompraActualizada"] = false;
                return RedirectToAction("Compras", "Cuenta");
            }

            return View(c);
        }
    }
}

Controllers/CorreoController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    [Authorize]
    public class CorreoController : Controller
    {
        private static ULSAVentasDataContext _db = ContextoEstatico.db;
        private static ULSAVentasDataContext db
        {
            get
            {
                return _db;
            }
        }

        // CORREOS
        // Y sus acciones de agregar, modificar y eliminar
        public ActionResult Index()
        {
            Usuario usuario = db.Usuario.First(u => u.usuario1 == User.Identity.Name);

            return PartialView(db.Correo.Where(c => c.idPersona == usuario.Persona.idPersona).ToList());
        }

        [HttpGet]
        public ActionResult AgregarCorreo()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult AgregarCorreo(Correo c)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Usuario usuario = db.Usuario.First(u => u.usuario1 == User.Identity.Name);

                    c.idPersona = usuario.Persona.idPersona;

                    db.Correo.InsertOnSubmit(c);

                    db.SubmitChanges();
                    TempData["correoCorreoAgregado"] = true;
                }
                catch (Exception)
                {
                    TempData["correoCorreoAgregado"] = false;
                }

                return PartialView();
            }

            return PartialView(c);
        }

        [HttpGet]
        public ActionResult ModificarCorreo(int? idCorreo = null)
        {
            if (idCorreo != null)
            {
                Correo c = db.Correo.First(c1 => c1.idCorreo == idCorreo);
                return PartialView(c);
            }

            return PartialView();
        }

        [HttpPost]
        public ActionResult ModificarCorreo(Correo c)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Correo c1 = db.Correo.First(c2 => c2.idCorreo == c.idCorreo);

                    c1.direccionDeCorreo = c.direccionDeCorreo;

                    db.SubmitChanges();
                    TempData["correoCorreoModificado"] = true;
                }
                catch (Exception)
                {
                    TempData["correoCorreoModificado"] = false;
                }

                return PartialView();
            }

            return PartialView(c);
        }

        [HttpGet]
        public ActionResult EliminarCorreo(int idCorreo)
        {
            try
            {
                Correo c = db.Correo.First(c1 => c1.idCorreo == idCorreo);
                db.Correo.DeleteOnSubmit(c);

                db.SubmitChanges();
                TempData["correoCorreoEliminado"] = true;
            }
            catch (Exception)
            {
                TempData["correoCorreoEliminado"] = false;
            }

            return PartialView();
        }
    }
}

Controllers/FavoritoController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    [Authorize]
    public class FavoritoController : Controller
    {
        private static ULSAVentasDataContext db
        {
            get
            {
                return ContextoEstatico.db;
            }
        }

        // GET: Favorito
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AgregarFavorito(int idPublicacion)
        {
            Publicacion p = null;
            Usuario u = null;
            Favorito f = null;

            try
            {
                u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);

                try
                {
                    f = db.Favorito.First(f1 => f1.idPublicacion == p.idPublicacion && f1.idUsuario == u.idUsuario);
                }
                catch (Exception)
                {
                    
                }

                if (f == null)
                {
                    f = new Favorito();

                    f.idPublicacion = p.idPublicacion;
                    f.idUsuario = u.idUsuario;

                    db.Favorito.InsertOnSubmit(f);
                    db.SubmitChanges();

                    TempData["favoritoFavoritoAgregado"] = true;
                }
            }
            catch (Exception)
            {
                TempData["favoritoFavoritoAgregado"] = false;
            }

            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult Eliminar(int idPublicacion)
        {
            Publicacion p = null;
            Usuario u = null;
            Favorito f = null;

            try
            {
                u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);

                f = db.Favorito.First(f1 => f1.idPublicacion == p.idPublicacion && f1.idUsuario == u.idUsuario);

                db.Favorito.DeleteOnSubmit(f);
                db.SubmitChanges();

                TempData["favoritoFavoritoEliminado"] = true;
            }
            catch (Exception)
            {
                TempData["favoritoFavoritoEliminado"] = false;
            }

            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

Controllers/PerfilController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    public class PerfilController : Controller
    {
        private static ULSAVentasDataContext db
        {
            get
            {
                return ContextoEstatico.db;
            }
        }

        // GET: Perfil
        public ActionResult Index(int idUsuario)
        {
            Usuario u = null;

            try
            {
                u = db.Usuario.First(u1 => u1.idUsuario == idUsuario);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(u);
        }

        public ActionResult RenderizarPerfil(int idUsuario)
        {
            Usuario u = null;

            try
            {
                u = db.Usuario.First(u1 => u1.idUsuario == idUsuario);

                List<Compra> compras = db.Compra.Where(c => c.idUsuario == u.idUsuario).ToList();
                List<Compra> ventas = db.Compra.Where(c => c.Publicacion.idUsuario == u.idUsuario).ToList();

                TempData["compras"] = compras.Count;
                TempData["ventas"] = ventas.Count;

                TempData["calificacionesCompradorPositivas"] = compras.Count(c => c.calificacionDeVenta == true);
                TempData["calificacionesCompradorNegativas"] = compras.Count(c => c.calificacionDeVenta == false);
                TempData["calificacionesCompradorNeutrales"] = compras.Count(c => c.calificacionDeVenta == null);

                TempData["calificacionesVendedorPositivas"] = ventas.Count(c => c.calificacionDeCompra == true);
                TempData["calificacionesVendedorNegativas"] = ventas.Count(c => c.calificacionDeCompra == false);
                TempData["calificacionesVendedorNeutrales"] = ventas.Count(c => c.calificacionDeCompra == null);

                TempData["publicacionesPerfil"] = db.Publicacion.Where(p => p.idUsuario == u.idUsuario).ToList();
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }

            return PartialView(u);
        }
    }
}

Controllers/TarjetaController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    [Authorize]
    public class TarjetaController : Controller
    {
        private ULSAVentasDataContext db
        {
            get
            {
                return ContextoEstatico.db;
            }
        }

        // Tarjetas
        // Y sus acciones de agregar, modificar y eliminar
        public ActionResult Index()
        {
            Usuario usuario = db.Usuario.First(u => u.usuario1 == User.Identity.Name);

            return PartialView(db.TarjetaDeCredito.Where(t => t.idPersona == usuario.Persona.idPersona).ToList());
        }

        [HttpGet]
        public ActionResult AgregarTarjeta()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult AgregarTarjeta(TarjetaDeCredito t)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Usuario usuario = db.Usuario.First(u => u.usuario1 == User.Identity.Name);

                    t.idPersona = usuario.Persona.idPersona;

                    db.TarjetaDeCredito.InsertOnSubmit(t);

                    db.SubmitChanges();
                    TempData["tarjetaTarjetaAgregada"] = true;
                }
                catch (Exception)
                {
                    TempData["tarjetaTarjetaAgregada"] = false;
                }

                return PartialView();
            }

            return PartialView(t);
        }

        [HttpGet]
        public ActionResult ModificarTarjeta(int? idTarjeta = null)
        {
            if (idTarjeta != null)
            {
                TarjetaDeCredito t = db.TarjetaDeCredito.First(t1 => t1.idTarjeta == idTarjeta);
                return PartialView(t);
            }

            return PartialView();
        }

        [HttpPost]
        public ActionResult ModificarTarjeta(TarjetaDeCredito t)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    TarjetaDeCredito t1 = db.TarjetaDeCredito.First(t2 => t2.idTarjeta == t.idTarjeta);

                    t1.numeroDeTarjeta = t.numeroDeTarjeta;

                    db.SubmitChanges();
                    TempData["tarjetaTarjetaModificada"] = true;
                }
                catch (Exception)
                {
                    TempData["tarjetaTarjetaModificada"] = false;
                }

                return PartialView();
            }

            return PartialView(t);
        }

        [HttpGet]
        public ActionResult EliminarTarjeta(int idTarjeta)
        {
            try
            {
                TarjetaDeCredito t = db.TarjetaDeCredito.First(t1 => t1.idTarjeta == idTarjeta);
                db.TarjetaDeCredito.DeleteOnSubmit(t);

                db.SubmitChanges();
                TempData["tarjetaTarjetaEliminada"] = true;
            }
            catch (Exception)
            {
                TempData["tarjetaTarjetaEliminada"] = false;
            }

            return PartialView();
        }
    }
}

Views/Cuenta/Compras.cshtml
@using _2017_05_24ULSAVentas.Models
@model List<Compra>

@{
    Layout = "~/Views/Cuenta/_LayoutCuenta.cshtml";
    ViewBag.Title = "Compras";
    ViewBag.cuentaPaginaActiva = "compras";

    bool? compraCompraRealizada = (bool?)TempData["compraCompraRealizada"];
    bool? compraCompraActualizada = (bool?)TempData["compraCompraActualizada"];
}

<small><strong>@(Model != null ? Model.Count.ToString() : "0")</strong> compras</small>
<hr />

@if (compraCompraActualizada == true)
{
    <div class="alert alert-success">
        Se han guardado tus cambios.
    </div>
}
else if (compraCompraActualizada == false)
{
    <div class="alert alert-success">
        Error al procesar tu solicitud.
    </div>
}

@if (compraCompraRealizada == true)
{
    <div class="alert alert-success">
        Compra realizada con éxito.
    </div>
}
else if (compraCompraRealizada == false)
{
    <div class="alert alert-danger">
        Error al procesar la compra
    </div>
}


@if (Model != null && Model.Count > 0)
{
    foreach (Compra c in Model)
    {
        <div class="row">

            <div class="col-md-3">
                @Html.Partial("~/Views/Publicacion/Imagen.cshtml", c.Publicacion)
            </div>
            <div class="col-md-6">
                @Html.Partial("~/Views/Publicacion/Descripcion.cshtml", c.Publicacion, new ViewDataDictionary { { "longitudCadena", 200 } })
                <br />
                <p><strong>@c.fecha.ToShortDateString()</strong> - Compraste @c.cantidad unidad(es)</p>
            </div>

            <div class="col-md-3">
                <h4 class="page-header">Acciones</h4>

                <div class="btn-group-vertical btn-block">
                    <a class="btn btn-default text-success" href="@Url.Action("VerDetalle", "Compra", new { idCompra = c.idCompra })"><span class="glyphicon glyphicon-pencil"></span> Ver detalle</a>
                </div>
            </div>
        </div>
        <hr />
    }
}
else
{
    <div class="alert alert-info">
        Parece que aún no has comprado algún artículo en el sitio. Utiliza la barra de búsqueda para comenzar, o checa los artículos sugeridos en la página principal.
    </div>
}

Views/Cuenta/Favoritos.cshtml
@using _2017_05_24ULSAVentas.Models
@model List<Publicacion>

@{
    Layout = "~/Views/Cuenta/_LayoutCuenta.cshtml";
    ViewBag.Title = "Favoritos";
    ViewBag.cuentaPaginaActiva = "favoritos";

    bool? favoritoFavoritoEliminado = (bool?)TempData["favoritoFavoritoEliminado"];
}

<small><strong>@(Model != null ? Model.Count.ToString() : "0")</strong> favoritos</small>
<hr />

@if (favoritoFavoritoEliminado == true)
{
    <div class="alert alert-success">
        Favorito eliminado.
    </div>
}
else if (favoritoFavoritoEliminado == false)
{
    <div class="alert alert-danger">
        No se ha podido eliminar el favorito.
    </div>
}

@if (Model != null && Model.Count > 0)
{
    foreach (Publicacion p in Model)
    {
        <div class="modal fade" id="modalEliminarFavorito@(p.idPublicacion)" role="dialog">

            <div class="modal-dialog">

                <div class="modal-content">

                    <div class="modal-header">
                        <h4 class="modal-title">Eliminar favorito</h4>
                    </div>

                    <div class="modal-body">

                        <div class="alert alert-warning">¿Está seguro que quiere eliminar la publicación "@p.titulo" de sus favoritos?</div>

                        <div class="btn-group btn-group-justified">
                            <a class="btn btn-danger" href="@Url.Action("Eliminar", "Favorito", new { idPublicacion = p.idPublicacion })">Sí</a>
                            <a class="btn btn-default" data-dismiss="modal">Cancelar</a>
                        </div>

                    </div>

                </div>

            </div>
        </div>

        <div class="row">

            <div class="col-md-3">
                @Html.Partial("~/Views/Publicacion/Imagen.cshtml", p)
            </div>
            <div class="col-md-6">
                @Html.Partial("~/Views/Publicacion/Descripcion.cshtml", p, new ViewDataDictionary { { "longitudCadena", 200 } })
            </div>

            <div class="col-md-3">
                <h4 class="page-header">Acciones</h4>

                <div class="btn-group-vertical btn-block">
                    <a class="btn btn-default" data-toggle="modal" href="#modalEliminarFavorito@(p.idPublicacion)"><div class="text-danger"><span class="glyphicon glyphicon-remove"></span> Eliminar</div></a>
                </div>
            </div>
        </div>
        <hr />
    }
}
else
{
    <div class="alert alert-info">
        Parece que aún no agregas ningún artículo a tus favoritos.
    </div>
}

Views/Cuenta/Index.cshtml
@using _2017_05_24ULSAVentas.Models
@model Usuario

@{
    Layout = "~/Views/Cuenta/_LayoutCuenta.cshtml";

    ViewBag.Title = "Mi cuenta";
    ViewBag.cuentaPaginaActiva = "resumen";
}

@Html.Action("RenderizarPerfil", "Perfil", new { idUsuario = Model.idUsuario })

Views/Cuenta/Informacion.cshtml
@using _2017_05_24ULSAVentas.Models

@model Persona

@{
    Layout = "~/Views/Cuenta/_LayoutCuenta.cshtml";
    ViewBag.Title = "Información";
    ViewBag.cuentaPaginaActiva = "informacion";

    bool? cuentaPersonaModificada = (bool?)TempData["cuentaPersonaModificada"];

}

@if (cuentaPersonaModificada == true)
{
    <div class="alert alert-success">
        Datos modificados con éxito.
    </div>
}
else if (cuentaPersonaModificada == false)
{
    <div class="alert alert-danger">
        Los datos no se han modificado.
    </div>
}

@using (Html.BeginForm("Informacion", "Cuenta", FormMethod.Post))
{
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(p => p.nombres)
        @Html.TextBoxFor(p => p.nombres, new { @class="form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.apellidoPaterno)
        @Html.TextBoxFor(p => p.apellidoPaterno, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.apellidoMaterno)
        @Html.TextBoxFor(p => p.apellidoMaterno, new { @class = "form-control" })
    </div>

    <input type="submit" class="btn btn-success" value="Guardar"/>
}

<hr />

<h3>Administrar</h3>

<div class="btn-group btn-group-justified">
    @Ajax.ActionLink("Direcciones", "Index", "Direccion", null, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divAdministracion" }, new { @class = "btn btn-primary" })
    @Ajax.ActionLink("Correos", "Index", "Correo", null, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divAdministracion" }, new { @class = "btn btn-primary" })
    @Ajax.ActionLink("Tarjetas", "Index", "Tarjeta", null, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divAdministracion" }, new { @class = "btn btn-primary" })
    @Ajax.ActionLink("Teléfonos", "Index", "Telefono", null, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divAdministracion" }, new { @class = "btn btn-primary" })
</div>

<div id="divAdministracion">

</div>

@{ 
    TempData["cuentaPersonaModificada"] = null;
}

Views/Cuenta/Publicaciones.cshtml
@using _2017_05_24ULSAVentas.Models
@model List<Publicacion>

@{
    Layout = "~/Views/Cuenta/_LayoutCuenta.cshtml";
    ViewBag.Title = "Publicaciones";
    ViewBag.cuentaPaginaActiva = "publicaciones";

    bool? publicacionesPublicacionEliminada = (bool?)TempData["publicacionesPublicacionEliminada"];
    bool? publicacionesPublicacionActualizada = (bool?)TempData["publicacionesPublicacionActualizada"];
    bool? publicacionesPublicacionCorrecta = (bool?)TempData["publicacionesPublicacionCorrecta"];
}
<small><strong>@(Model != null ? Model.Count.ToString() : "0")</strong> publicaciones</small>
<hr />

@if (publicacionesPublicacionEliminada == true)
{
    <div class="alert alert-warning">
        Publicación eliminada con éxito.
    </div>
}
else if (publicacionesPublicacionEliminada == false)
{
    <div class="alert alert-danger">
        No se eliminó la publicación.
    </div>
}

@if (publicacionesPublicacionActualizada == true)
{
    <div class="alert alert-success">
        Publicación actualizada con éxito.
    </div>
}
else if (publicacionesPublicacionActualizada == false)
{
    <div class="alert alert-danger">
        No se actualizó la publicación.
    </div>
}

@if (publicacionesPublicacionCorrecta == true)
{
    <div class="alert alert-success">
        Se publicó el artículo con éxito.
    </div>
}
else if (publicacionesPublicacionCorrecta == false)
{
    <div class="alert alert-danger">
        No se publicó el artículo.
    </div>
}

@if (Model != null && Model.Count > 0)
{
    foreach (Publicacion p in Model)
    {
        <div class="modal fade" id="modalEliminarPublicacion@(p.idPublicacion)" role="dialog">

            <div class="modal-dialog">

                <div class="modal-content">

                    <div class="modal-header">
                        <h4 class="modal-title">Eliminar publicación</h4>
                    </div>

                    <div class="modal-body">

                        <div class="alert alert-warning">¿Está seguro que quiere eliminar la publicación "@p.titulo"?</div>

                        <div class="btn-group btn-group-justified">
                            <a class="btn btn-danger" href="@Url.Action("Eliminar", "Publicaciones", new { idPublicacion = p.idPublicacion })">Sí</a>
                            <a class="btn btn-default" data-dismiss="modal">Cancelar</a>
                        </div>

                    </div>

                </div>

            </div>
        </div>

        <div class="row">

            <div class="col-md-3">
                @Html.Partial("~/Views/Publicacion/Imagen.cshtml", p)
            </div>
            <div class="col-md-6">
                @Html.Partial("~/Views/Publicacion/Descripcion.cshtml", p, new ViewDataDictionary { { "longitudCadena", 200 } })
            </div>
            
            <div class="col-md-3">
                <h4 class="page-header">Acciones</h4>

                <div class="btn-group-vertical btn-block">
                    <a class="btn btn-default" href="@Url.Action("ModificarPublicacion", "Publicaciones", new { idPublicacion = p.idPublicacion })"><span class="glyphicon glyphicon-pencil"></span> Modificar</a>
                    <a class="btn btn-default" data-toggle="modal" href="#modalEliminarPublicacion@(p.idPublicacion)"><div class="text-danger"><span class="glyphicon glyphicon-remove"></span> Eliminar</div></a>
                </div>
            </div>
        </div>
        <hr />
    }
}
else
{
    <div class="alert alert-info">
        Parece que aún no publicas ningún artículo. Comienza haciendo clic en el signo <span class="glyphicon glyphicon-plus"></span> de la barra de navegación.
    </div>
}

@{
    TempData["publicacionesPublicacionEliminada"] = null;
    TempData["publicacionesPublicacionActualizada"] = null;
}

Views/Cuenta/Ventas.cshtml
@using _2017_05_24ULSAVentas.Models
@model List<Compra>

@{
    Layout = "~/Views/Cuenta/_LayoutCuenta.cshtml";
    ViewBag.Title = "Ventas";
    ViewBag.cuentaPaginaActiva = "ventas";
    
    bool? compraCompraActualizada = (bool?)TempData["compraCompraActualizada"];
}

<small><strong>@(Model != null ? Model.Count.ToString() : "0")</strong> ventas</small>
<hr />

@if (compraCompraActualizada == true)
{
    <div class="alert alert-success">
        Se han guardado tus cambios.
    </div>
}
else if (compraCompraActualizada == false)
{
    <div class="alert alert-success">
        Error al procesar tu solicitud.
    </div>
}

@if (Model != null && Model.Count > 0)
{
    foreach (Compra c in Model)
    {
        <div class="row">

            <div class="col-md-3">
                @Html.Partial("~/Views/Publicacion/Imagen.cshtml", c.Publicacion)
            </div>
            <div class="col-md-6">
                @Html.Partial("~/Views/Publicacion/Descripcion.cshtml", c.Publicacion, new ViewDataDictionary { { "longitudCadena", 200 } })
                <br />
                <p><strong>@c.fecha.ToShortDateString() - <a href="@Url.Action("Index", "Perfil", new { idUsuario = c.Usuario.idUsuario} )">@c.Usuario.usuario1</a></strong> compró @c.cantidad unidad(es)</p>
            </div>

            <div class="col-md-3">
                <h4 class="page-header">Acciones</h4>

                <div class="btn-group-vertical btn-block">
                    <a class="btn btn-default text-success" href="@Url.Action("VerDetalle", "Compra", new { idCompra = c.idCompra })"><span class="glyphicon glyphicon-pencil"></span> Ver detalle</a>
                </div>
            </div>
        </div>
        <hr />
    }
}
else
{
    <div class="alert alert-info">
        Parece que aún no tienes ventas en el sitio.
    </div>
}