Controllers/ComentarioController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    [Authorize]
    public class ComentarioController : Controller
    {
        private static ULSAVentasDataContext _db = ContextoEstatico.db;
        private static ULSAVentasDataContext db
        {
            get
            {
                return _db;
            }
        }

        // GET: Comentario
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult VerComentarios(int idPublicacion)
        {
            Publicacion p = null;
            List<Comentario> comentarios = new List<Comentario>();

            try
            {
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);
                comentarios = db.Comentario.Where(c => c.idPublicacion == p.idPublicacion).OrderByDescending(c => c.idComentario).ToList();
            }
            catch (Exception)
            {
                
            }

            return PartialView(comentarios);
        }

        [HttpPost]
        public ActionResult VerComentarios(string comentario, int idPublicacion)
        {
            try
            {
                Usuario u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);

                Comentario c = new Comentario();

                c.comentario1 = comentario;
                c.fecha = DateTime.Now;
                c.idPublicacion = idPublicacion;
                c.idUsuario = u.idUsuario;

                db.Comentario.InsertOnSubmit(c);
                db.SubmitChanges();

                TempData["comentarioComentarioAgregado"] = true;
            }
            catch (Exception)
            {
                TempData["comentarioComentarioAgregado"] = false;
                throw;
            }

            return RedirectToAction("VerPublicacion", "Publicaciones", new { idPublicacion = idPublicacion});
        }
    }
}

Controllers/PerfilController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    public class PerfilController : Controller
    {
        private static ULSAVentasDataContext db
        {
            get
            {
                return ContextoEstatico.db;
            }
        }

        // GET: Perfil
        public ActionResult Index(int idUsuario)
        {
            Usuario u = null;

            try
            {
                u = db.Usuario.First(u1 => u1.idUsuario == idUsuario);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(u);
        }

        public ActionResult RenderizarPerfil(int idUsuario)
        {
            Usuario u = null;

            try
            {
                u = db.Usuario.First(u1 => u1.idUsuario == idUsuario);

                List<Compra> compras = db.Compra.Where(c => c.idUsuario == u.idUsuario).ToList();
                List<Compra> ventas = db.Compra.Where(c => c.Publicacion.idUsuario == u.idUsuario).ToList();

                TempData["compras"] = compras.Count;
                TempData["ventas"] = ventas.Count;

                TempData["calificacionesCompradorPositivas"] = compras.Count(c => c.calificacionDeVenta == true);
                TempData["calificacionesCompradorNegativas"] = compras.Count(c => c.calificacionDeVenta == false);
                TempData["calificacionesCompradorNeutrales"] = compras.Count(c => c.calificacionDeVenta == null);

                TempData["calificacionesVendedorPositivas"] = ventas.Count(c => c.calificacionDeCompra == true);
                TempData["calificacionesVendedorNegativas"] = ventas.Count(c => c.calificacionDeCompra == false);
                TempData["calificacionesVendedorNeutrales"] = ventas.Count(c => c.calificacionDeCompra == null);

                TempData["publicacionesPerfil"] = db.Publicacion.Where(p => p.idUsuario == u.idUsuario).ToList();
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }

            return PartialView(u);
        }
    }
}

Views/Comentario/VerComentarios.cshtml
@using _2017_05_24ULSAVentas.Models
@model List<Comentario>

<h3 class="page-header">Comentarios@(Model != null ? " (" + Model.Count + ")" : "0")</h3>
<p>
    @if (Model != null && Model.Count > 0)
    {
        <div class="panel-group">

            @foreach (Comentario c in Model)
            {
                <div class="panel @(Request.IsAuthenticated && c.Usuario.usuario1 == User.Identity.Name ? "panel-success" : "panel-default")">
                    <div class="panel-heading">
                        @c.fecha.ToShortDateString() - <strong><a href="@Url.Action("Index", "Perfil", new { idUsuario = c.Usuario.idUsuario })">@c.Usuario.usuario1</a></strong> dijo...
                    </div>
                    <div class="panel-body">
                        @c.comentario1
                    </div>
                </div>
            }

        </div>
    }
    else
    {
        <div class="alert alert-info">
            Parece que esta publicación no tiene comentarios aún ¡Sé el primero, <strong>soyez le premier</strong>!
        </div>
    }
</p>

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("VerComentarios", "Comentario", FormMethod.Post))
    {
        <input type="hidden" name="idPublicacion" value="@Session["idPublicacion"]"/>

        <div class="form-group">
            <label>Comenta</label>
            <textarea name="comentario" placeholder="Tu comentario aquí" class="form-control"></textarea>
        </div>
        
        <input type="submit" class="btn btn-success" value="Comentar"/>
    }
}
else
{
    <div class="alert alert-success">
        Regístrate o inicia sesión para poder comentar.
    </div>
}