Controllers/CompraController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    [Authorize]
    public class CompraController : Controller
    {
        private ULSAVentasDataContext db
        {
            get
            {
                return ContextoEstatico.db;
            }
        }

        // GET: Compra
        public ActionResult Index(int idPublicacion)
        {
            Publicacion p = null;
            Usuario u = null;

            try
            {
                u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);

                List<Direccion> direcciones = db.Direccion.Where(d => d.idPersona == u.Persona.idPersona).ToList();
                List<TarjetaDeCredito> tarjetas = db.TarjetaDeCredito.Where(t => t.idPersona == u.Persona.idPersona).ToList();

                TempData["compraDireccionesUsuario"] = direcciones;
                TempData["compraTarjetasUsuario"] = tarjetas;

            }
            catch (Exception)
            {
                return Redirect(Request.UrlReferrer.ToString());
            }

            return View(p);
        }

        [HttpPost]
        public ActionResult Comprar(int idPublicacion, int cantidad, int idTarjeta, int idDireccion)
        {
            Publicacion p = null;
            TarjetaDeCredito t = null;
            Direccion d = null;
            Usuario u = null;

            Compra c = null;

            try
            {
                u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);
                t = db.TarjetaDeCredito.First(t1 => t1.idTarjeta == idTarjeta);
                d = db.Direccion.First(d1 => d1.idDireccion == idDireccion);

                c = new Compra();

                c.cantidad = cantidad;
                c.fecha = DateTime.Now;
                c.idDireccion = d.idDireccion;
                c.idPublicacion = p.idPublicacion;
                c.idTarjeta = t.idTarjeta;
                c.idUsuario = u.idUsuario;

                p.cantidad -= cantidad;

                db.Compra.InsertOnSubmit(c);
                db.SubmitChanges();

                TempData["compraCompraRealizada"] = true;
            }
            catch (Exception)
            {
                TempData["compraCompraRealizada"] = false;
                return Redirect(Request.UrlReferrer.ToString());
            }

            return RedirectToAction("Compras", "Cuenta");
        }

        [HttpGet]
        public ActionResult VerDetalle(int idCompra)
        {
            Compra c = null;

            try
            {
                c = db.Compra.First(c1 => c1.idCompra == idCompra);
            }
            catch (Exception)
            {
                return RedirectToAction("Compras", "Cuenta");
            }

            return View(c);
        }

        [HttpPost]
        public ActionResult VerDetalle(int idCompra, bool? calificacionDeCompra, string comentarioDeCompra, bool? calificacionDeVenta, string comentarioDeVenta)
        {
            Compra c = null;

            try
            {
                c = db.Compra.First(c1 => c1.idCompra == idCompra);

                c.calificacionDeCompra = calificacionDeCompra;
                c.calificacionDeVenta = calificacionDeVenta;
                c.comentarioDeCompra = comentarioDeCompra;
                c.comentarioDeVenta = comentarioDeVenta;

                db.SubmitChanges();

                TempData["compraCompraActualizada"] = true;
            }
            catch (Exception)
            {
                TempData["compraCompraActualizada"] = false;
                return RedirectToAction("Compras", "Cuenta");
            }

            return View(c);
        }
    }
}

Controllers/FavoritoController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    [Authorize]
    public class FavoritoController : Controller
    {
        private static ULSAVentasDataContext db
        {
            get
            {
                return ContextoEstatico.db;
            }
        }

        // GET: Favorito
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AgregarFavorito(int idPublicacion)
        {
            Publicacion p = null;
            Usuario u = null;
            Favorito f = null;

            try
            {
                u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);

                try
                {
                    f = db.Favorito.First(f1 => f1.idPublicacion == p.idPublicacion && f1.idUsuario == u.idUsuario);
                }
                catch (Exception)
                {
                    
                }

                if (f == null)
                {
                    f = new Favorito();

                    f.idPublicacion = p.idPublicacion;
                    f.idUsuario = u.idUsuario;

                    db.Favorito.InsertOnSubmit(f);
                    db.SubmitChanges();

                    TempData["favoritoFavoritoAgregado"] = true;
                }
            }
            catch (Exception)
            {
                TempData["favoritoFavoritoAgregado"] = false;
            }

            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult Eliminar(int idPublicacion)
        {
            Publicacion p = null;
            Usuario u = null;
            Favorito f = null;

            try
            {
                u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);

                f = db.Favorito.First(f1 => f1.idPublicacion == p.idPublicacion && f1.idUsuario == u.idUsuario);

                db.Favorito.DeleteOnSubmit(f);
                db.SubmitChanges();

                TempData["favoritoFavoritoEliminado"] = true;
            }
            catch (Exception)
            {
                TempData["favoritoFavoritoEliminado"] = false;
            }

            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

Controllers/PerfilController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    public class PerfilController : Controller
    {
        private static ULSAVentasDataContext db
        {
            get
            {
                return ContextoEstatico.db;
            }
        }

        // GET: Perfil
        public ActionResult Index(int idUsuario)
        {
            Usuario u = null;

            try
            {
                u = db.Usuario.First(u1 => u1.idUsuario == idUsuario);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(u);
        }

        public ActionResult RenderizarPerfil(int idUsuario)
        {
            Usuario u = null;

            try
            {
                u = db.Usuario.First(u1 => u1.idUsuario == idUsuario);

                List<Compra> compras = db.Compra.Where(c => c.idUsuario == u.idUsuario).ToList();
                List<Compra> ventas = db.Compra.Where(c => c.Publicacion.idUsuario == u.idUsuario).ToList();

                TempData["compras"] = compras.Count;
                TempData["ventas"] = ventas.Count;

                TempData["calificacionesCompradorPositivas"] = compras.Count(c => c.calificacionDeVenta == true);
                TempData["calificacionesCompradorNegativas"] = compras.Count(c => c.calificacionDeVenta == false);
                TempData["calificacionesCompradorNeutrales"] = compras.Count(c => c.calificacionDeVenta == null);

                TempData["calificacionesVendedorPositivas"] = ventas.Count(c => c.calificacionDeCompra == true);
                TempData["calificacionesVendedorNegativas"] = ventas.Count(c => c.calificacionDeCompra == false);
                TempData["calificacionesVendedorNeutrales"] = ventas.Count(c => c.calificacionDeCompra == null);

                TempData["publicacionesPerfil"] = db.Publicacion.Where(p => p.idUsuario == u.idUsuario).ToList();
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }

            return PartialView(u);
        }
    }
}

Controllers/PruebasController.cs
using _2017_05_24ULSAVentas.Models;
using _2017_05_24ULSAVentas.ServicioLocal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    public class PruebasController : Controller
    {
        private static ULSAVentasDataContext _db = ContextoEstatico.db;
        private static ULSAVentasDataContext db
        {
            get
            {
                return _db;
            }
        }


        // GET: Pruebas
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Direccion.ToList());
        }

        public ActionResult MapaParcial(string lat, string lng)
        {
            string[] s = { lat, lng };
            return PartialView(s);
        }

        [HttpGet]
        public ActionResult ConsumirServicio()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ConsumirServicio(int idPublicacion, int cantidad)
        {
            ServicioExamenSoapClient cliente = new ServicioExamenSoapClient();

            double d = cliente.calcularTotal(idPublicacion, cantidad);

            return View(d);
        }
    }
}

Controllers/PublicacionesController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Linq;

namespace _2017_05_24ULSAVentas.Controllers
{
    [Authorize]
    public class PublicacionesController : Controller
    {
        private static ULSAVentasDataContext _db = ContextoEstatico.db;
        private static ULSAVentasDataContext db
        {
            get
            {
                return _db;
            }
        }

        [HttpGet]
        public ActionResult Publicar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Publicar(Publicacion p)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Usuario u1 = db.Usuario.First(u => u.usuario1 == User.Identity.Name);
                    p.idUsuario = u1.idUsuario;

                    db.Publicacion.InsertOnSubmit(p);
                    db.SubmitChanges();

                    TempData["publicacionesPublicacionCorrecta"] = true;
                }
                catch (Exception)
                {
                    TempData["publicacionesPublicacionCorrecta"] = false;
                    return View(p);
                }

                return RedirectToAction("Publicaciones", "Cuenta");
            }
            else
            {
                return View(p);
            }
        }

        [HttpGet]
        public ActionResult ModificarPublicacion(int? idPublicacion)
        {
            if (idPublicacion != null)
            {
                try
                {
                    Publicacion p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);
                    Usuario u1 = db.Usuario.First(u => u.usuario1 == User.Identity.Name);

                    if (p.idUsuario == u1.idUsuario)
                        return View(p);
                }
                catch (Exception)
                {
                    
                }
            }

            return RedirectToAction("Publicaciones", "Cuenta");
        }

        [HttpPost]
        public ActionResult ModificarPublicacion(Publicacion p)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Publicacion p1 = db.Publicacion.First(p2 => p2.idPublicacion == p.idPublicacion);

                    p1.cantidad = p.cantidad;
                    p1.descripcion = p.descripcion;
                    p1.direccionImagen = p.direccionImagen;
                    p1.precio = p.precio;
                    p1.titulo = p.titulo;

                    db.SubmitChanges();

                    TempData["publicacionesPublicacionActualizada"] = true;
                }
                catch (Exception)
                {
                    TempData["publicacionesPublicacionActualizada"] = false;
                    return View(p);
                }

                return RedirectToAction("Publicaciones", "Cuenta");
            }
            else
            {
                return View(p);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int? idPublicacion)
        {
            if (idPublicacion != null)
            {
                try
                {
                    Usuario u = db.Usuario.First(u1 => u1.usuario1 == User.Identity.Name);
                    Publicacion p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);

                    if (p.idUsuario == u.idUsuario)
                    {
                        db.Publicacion.DeleteOnSubmit(p);
                        db.SubmitChanges();

                        TempData["publicacionesPublicacionEliminada"] = true;
                    }
                }
                catch (Exception)
                {
                    TempData["publicacionesPublicacionEliminada"] = false;
                }
            }

            return RedirectToAction("Publicaciones", "Cuenta");
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Buscar(string q)
        {
            if (q == null || q.Trim() == "")
            {
                return Redirect(Request.UrlReferrer.ToString());
            }

            List<Publicacion> publicaciones = new List<Publicacion>();

            try
            {
                publicaciones = db.Publicacion.Where(p => p.titulo.Contains(q.Trim())).ToList();
            }
            catch (Exception)
            {
                
            }

            TempData["criterioDeBusqueda"] = q;

            return View(publicaciones);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult VerPublicacion(int? idPublicacion)
        {
            if (idPublicacion == null)
                return RedirectToAction("Index", "Home");

            Publicacion p = null;
            Direccion d = null;

            try
            {
                p = db.Publicacion.First(p1 => p1.idPublicacion == idPublicacion);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                d = p.Usuario.Persona.Direccion.First(d1 => true);
            }
            catch (Exception)
            {
                
            }

            TempData["publicacionesDireccion"] = d;

            return View(p);
        }
    }
}

Views/Publicaciones/Buscar.cshtml
@using _2017_05_24ULSAVentas.Models
@model List<Publicacion>

@{
    ViewBag.Title = "Búsqueda de publicaciones";
}

<h3 class="page-header">Búsqueda de "@TempData["criterioDeBusqueda"]" (@Model.Count resultados)</h3>

@if (Model != null && Model.Count > 0)
{
    foreach (Publicacion p in Model)
    {
        <div class="row">

            <div class="col-md-2">
                @Html.Partial("~/Views/Publicacion/Imagen.cshtml", p)
            </div>
            <div class="col-md-10">
                @Html.Partial("~/Views/Publicacion/Descripcion.cshtml", p, new ViewDataDictionary { { "longitudCadena", 400 } })
            </div>

        </div>
        <hr />
    }
}
else
{
    <div class="alert alert-info">
        Lo sentimos, sus criterios de búsqueda no produjeron algún resultado.
    </div>
}

Views/Publicaciones/ModificarPublicacion.cshtml
@using _2017_05_24ULSAVentas.Models
@model Publicacion

@{
    ViewBag.Title = "Modificar publicación";
    ViewBag.layoutPaginaActiva = "publicar";

    bool? publicacionesPublicacionActualizada = (bool?)TempData["publicacionesPublicacionActualizada"];
}

<h2 class="page-header">Publica un producto</h2>

@if (publicacionesPublicacionActualizada == true)
{
    <div class="alert alert-success">
        Publicación actualizada con éxito.
    </div>
}
else if (publicacionesPublicacionActualizada == false)
{
    <div class="alert alert-danger">
        Error al actualizar la publicación.
    </div>
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="row">

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(p => p.titulo)
                @Html.TextBoxFor(p => p.titulo, new { @class = "form-control", placeholder = "Título de la publicación" })
            </div>

            <div class="form-group">
                @Html.LabelFor(p => p.precio)
                @Html.TextBoxFor(p => p.precio, new { @class = "form-control", @type = "number", value = "0.00", min = "0", step = "any" })
            </div>

            <div class="form-group">
                @Html.LabelFor(p => p.cantidad)
                @Html.TextBoxFor(p => p.cantidad, new { @class = "form-control", @type = "number", value = "5", min = "0", step = "1" })
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(p => p.descripcion)<br />
                @Html.TextAreaFor(p => p.descripcion, new { @class = "form-control", placeholder = "Descripción del producto" })
            </div>

            <div class="form-group">
                @Html.LabelFor(p => p.direccionImagen)
                @Html.TextBoxFor(p => p.direccionImagen, new { @class = "form-control", placeholder = "URL de la imagen" })
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <input type="submit" value="Actualizar" class="btn btn-success btn-block btn-lg" />
        </div>
    </div>
}

Views/Publicaciones/Publicar.cshtml
@using _2017_05_24ULSAVentas.Models
@model Publicacion

@{
    ViewBag.Title = "Publicar";
    ViewBag.layoutPaginaActiva = "publicar";

    bool? publicacionesPublicacionCorrecta = (bool?)TempData["publicacionesPublicacionCorrecta"];
}

<h2 class="page-header">Publica un producto</h2>

@if (publicacionesPublicacionCorrecta == true)
{
    <div class="alert alert-success">Publicación realizada con éxito.</div>
}
else if (publicacionesPublicacionCorrecta == false)
{
    <div class="alert alert-danger">Error al publicar el artículo.</div>
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="row">

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(p => p.titulo)
                @Html.TextBoxFor(p => p.titulo, new { @class = "form-control", placeholder = "Título de la publicación" })
            </div>

            <div class="form-group">
                @Html.LabelFor(p => p.precio)
                @Html.TextBoxFor(p => p.precio, new { @class = "form-control", @type ="number", min="0", step="any", value = "0.00" })
            </div>

            <div class="form-group">
                @Html.LabelFor(p => p.cantidad)
                @Html.TextBoxFor(p => p.cantidad, new { @class = "form-control", @type = "number", min = "0", step = "1", value = "5" })
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(p => p.descripcion)<br />
                @Html.TextAreaFor(p => p.descripcion, new { @class = "form-control", placeholder = "Descripción del producto" })
            </div>

            <div class="form-group">
                @Html.LabelFor(p => p.direccionImagen)
                @Html.TextBoxFor(p => p.direccionImagen, new { @class = "form-control", placeholder = "URL de la imagen" })
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <input type="submit" value="Publicar" class="btn btn-success btn-block btn-lg" />
        </div>
    </div>
}

Views/Publicaciones/VerPublicacion.cshtml
@using _2017_05_24ULSAVentas.Models

@model Publicacion

@{
    ViewBag.Title = Model.titulo;
    Session["idPublicacion"] = Model.idPublicacion;

    bool? comentarioComentarioAgregado = (bool?)TempData["comentarioComentarioAgregado"];
    bool? favoritoFavoritoAgregado = (bool?)TempData["favoritoFavoritoAgregado"];

    Direccion d = (Direccion)TempData["publicacionesDireccion"];
}

@if (d != null)
{
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBosm5YSmCWuTxoAYG2GGSFF3yLamdXNJE"></script>
    <div class="modal fade" id="modalSucursal" role="dialog">

        <div class="modal-dialog">

            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Mapa de sucursal</h4>
                </div>

                <div class="modal-body" id="divAgregarDireccion">
                    @Html.Action("MapaParcial", "Pruebas", new { lat = d.latitud, lng = d.longitud })
                </div>

            </div>

        </div>
    </div>

    <script>
        var iniciado = false;

        $("#modalSucursal").on('shown.bs.modal', function () {
            if (!iniciado) {
                initMap();
                iniciado = true;
            }
        });
    </script>
}

<div class="row">
    <div class="col-md-offset-1 col-md-10">


        <h2 class="page-header"><strong>@Model.titulo</strong> <small class="pull-right">por <strong><a href="@Url.Action("Index", "Perfil", new { idUsuario = Model.Usuario.idUsuario })">@Model.Usuario.usuario1</a></strong></small></h2>

        @if (comentarioComentarioAgregado == true)
        {
            <div class="alert alert-success">
                ¡Comentaste con éxito!
            </div>
        }
        else if (comentarioComentarioAgregado == false)
        {
            <div class="alert alert-danger">
                No pudimos agregar tu comentario.
            </div>
        }

        @if (favoritoFavoritoAgregado == true)
        {
            <div class="alert alert-success">
                Publicación agregada a favoritos.
            </div>
        }
        else if (favoritoFavoritoAgregado == false)
        {
            <div class="alert alert-danger">
                No pudimos agregar la publicación a favoritos.
            </div>
        }

        <div class="row">

            <div class="col-md-4 text-center">
                <img src="@Model.direccionImagen" class="img-thumbnail img-responsive" />
            </div>

            <div class="col-md-4">
                <h4><span class="text-primary">Descripción</span></h4>
                <hr />
                <p class="text-justify">
                    @Model.descripcion
                </p>
            </div>

            <div class="col-md-4 text-center">
                <h2 class="text-danger">
                    <strong>$ @string.Format("{0:n}", Model.precio)</strong>
                    <br />
                    <small><span class="label @(Model.cantidad > 6 ? "label-primary" : Model.cantidad > 3 ? "label-success" : Model.cantidad == 0 ? "label-danger" : "label-warning")">@Model.cantidad unidad(es) disponibles</span></small>
                </h2>

                <br />

                <p class="text-muted">
                    <span class="glyphicon glyphicon-map-marker"></span>&nbsp;
                    @if (d != null)
                    {
                        @:Sucursal en
                        @d.estado
                        @:(<a data-toggle="modal" href="#modalSucursal">Ver mapa</a>)
                    }
                    else
                    {
                        @:El vendedor no ha registrado sucursales
                    }
                </p>

                <br />

                <a class="btn btn-lg btn-block @(Model.cantidad > 0 ? "btn-success" : "btn-warning disabled")" href="@Url.Action("Index", "Compra", new { idPublicacion = Model.idPublicacion })">
                    @(Model.cantidad > 0 ? "Comprar" : "Producto agotado")
                </a>
                <a class="btn btn-danger btn-sm btn-block" href="@Url.Action("AgregarFavorito", "Favorito", new { idPublicacion = Model.idPublicacion })">
                    <span class="glyphicon glyphicon-heart"></span> Agregar a favoritos
                </a>
            </div>

            <div class="col-md-12">
                @Html.Action("VerComentarios", "Comentario", new { idPublicacion = Model.idPublicacion })
            </div>

        </div>


    </div>
</div>