Controllers/DireccionController.cs
using _2017_05_24ULSAVentas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    [Authorize]
    public class DireccionController : Controller
    {
        private static ULSAVentasDataContext _db = ContextoEstatico.db;
        private static ULSAVentasDataContext db
        {
            get
            {
                return _db;
            }
        }

        // GET: Direccion
        public ActionResult Index()
        {
            Usuario usuario = db.Usuario.First(u => u.usuario1 == User.Identity.Name);

            return PartialView(db.Direccion.Where(d => d.idPersona == usuario.Persona.idPersona).ToList());
        }

        [HttpGet]
        public ActionResult AgregarDireccion()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult AgregarDireccion(Direccion d)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Usuario usuario = db.Usuario.First(u => u.usuario1 == User.Identity.Name);

                    d.idPersona = usuario.Persona.idPersona;

                    db.Direccion.InsertOnSubmit(d);

                    db.SubmitChanges();
                    TempData["direccionDireccionAgregada"] = true;
                }
                catch (Exception)
                {
                    TempData["direccionDireccionAgregada"] = false;
                }

                return PartialView();
            }

            return PartialView(d);
        }

        [HttpGet]
        public ActionResult ModificarDireccion(int? idDireccion = null)
        {
            if (idDireccion != null)
            {
                Direccion d = db.Direccion.First(d1 => d1.idDireccion == idDireccion);
                return PartialView(d);
            }

            return PartialView();
        }

        [HttpPost]
        public ActionResult ModificarDireccion(Direccion d)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Direccion d1 = db.Direccion.First(d2 => d2.idDireccion == d.idDireccion);

                    d1.calle = d.calle;
                    d1.codigoPostal = d.codigoPostal;
                    d1.colonia = d.colonia;
                    d1.estado = d.estado;
                    d1.latitud = d.latitud;
                    d1.longitud = d.longitud;
                    d1.numeroExterior = d.numeroExterior;
                    d1.numeroInterior = d.numeroInterior;
                    
                    db.SubmitChanges();
                    TempData["direccionDireccionModificada"] = true;
                }
                catch (Exception)
                {
                    TempData["direccionDireccionModificada"] = false;
                }

                return PartialView();
            }

            return PartialView(d);
        }

        [HttpGet]
        public ActionResult EliminarDireccion(int idDireccion)
        {
            try
            {
                Direccion d = db.Direccion.First(d1 => d1.idDireccion == idDireccion);
                db.Direccion.DeleteOnSubmit(d);

                db.SubmitChanges();
                TempData["direccionDireccionEliminada"] = true;
            }
            catch (Exception)
            {
                TempData["direccionDireccionEliminada"] = false;
            }

            return PartialView();
        }
    }
}

Controllers/PruebasController.cs
using _2017_05_24ULSAVentas.Models;
using _2017_05_24ULSAVentas.ServicioLocal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2017_05_24ULSAVentas.Controllers
{
    public class PruebasController : Controller
    {
        private static ULSAVentasDataContext _db = ContextoEstatico.db;
        private static ULSAVentasDataContext db
        {
            get
            {
                return _db;
            }
        }


        // GET: Pruebas
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Direccion.ToList());
        }

        public ActionResult MapaParcial(string lat, string lng)
        {
            string[] s = { lat, lng };
            return PartialView(s);
        }

        [HttpGet]
        public ActionResult ConsumirServicio()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ConsumirServicio(int idPublicacion, int cantidad)
        {
            ServicioExamenSoapClient cliente = new ServicioExamenSoapClient();

            double d = cliente.calcularTotal(idPublicacion, cantidad);

            return View(d);
        }
    }
}

Views/Direccion/AgregarDireccion.cshtml
@using _2017_05_24ULSAVentas.Models
@model Direccion

@{
    bool? direccionDireccionAgregada = (bool?)TempData["direccionDireccionAgregada"];
}

@if (direccionDireccionAgregada == true)
{
    <div class="alert alert-success">
        Dirección agregada con éxito.
    </div>
}
else if (direccionDireccionAgregada == false)
{
    <div class="alert alert-danger">
        No se ha agregado la dirección.
    </div>
}

@using (Ajax.BeginForm("AgregarDireccion", "Direccion", new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divAgregarDireccion", HttpMethod = "POST" }))
{
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(d => d.calle)
                @Html.TextBoxFor(d => d.calle, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.numeroExterior) (Opcional)
                @Html.TextBoxFor(d => d.numeroExterior, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(d => d.numeroInterior) (Opcional)
                @Html.TextBoxFor(d => d.numeroInterior, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(d => d.colonia)
                @Html.TextBoxFor(d => d.colonia, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.codigoPostal)
                @Html.TextBoxFor(d => d.codigoPostal, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.estado)
                @Html.TextBoxFor(d => d.estado, new { @class = "form-control" })
            </div>
        </div>

        <div class="col-md-12">
            <h4 class="page-header"><span class="glyphicon glyphicon-map-marker"></span> Opciones de mapa (opcionales)</h4>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(d => d.latitud)
                @Html.TextBoxFor(d => d.latitud, new { @class = "form-control" })
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(d => d.longitud)
                @Html.TextBoxFor(d => d.longitud, new { @class = "form-control" })
            </div>
        </div>

        <div class="col-md-4 col-md-offset-4">
            <input type="submit" class="btn btn-success btn-block" value="Agregar" />
        </div>
    </div>
}

@{
    TempData["direccionDireccionAgregada"] = null;
}

Views/Direccion/EliminarDireccion.cshtml
@{
    bool? direccionDireccionEliminada = (bool?)TempData["direccionDireccionEliminada"];
}

@if (direccionDireccionEliminada == true)
{
    <div class="alert alert-warning">
        Dirección eliminada con éxito.
    </div>
}
else if (direccionDireccionEliminada == false)
{
    <div class="alert alert-danger">
        La dirección no se eliminó.
    </div>
}

<div class="btn-group btn-group-justified">
    <a class="btn btn-default btn-block" data-dismiss="modal" onclick="@("window.location.href='" + @Url.Action("Informacion", "Cuenta") + "'");">Cerrar</a>
</div>

@{
    TempData["direccionDireccionEliminada"] = null;
}

Views/Direccion/Index.cshtml
@using _2017_05_24ULSAVentas.Models
@model List<Direccion>

<h3 class="page-header"><span class="glyphicon glyphicon-map-marker"></span> Direcciones</h3>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBosm5YSmCWuTxoAYG2GGSFF3yLamdXNJE"></script>

<script>
    function mostrarModalModificarDireccion() {
        $("#modalModificarDireccion").modal("toggle");
    }

    function mostrarModalMapaParcial() {
        $("#modalMapaParcial").modal("toggle");
    }

    $("#modalMapaParcial").on('shown.bs.modal', function () {
        initMap();
    });
</script>

<p>
    <a data-toggle="modal" href="#modalAgregarDireccion"><span class="glyphicon glyphicon-plus"></span> Agregar</a>
</p>

<div class="modal fade" id="modalAgregarDireccion" role="dialog">

    <div class="modal-dialog modal-lg">

        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Agregar dirección</h4>
            </div>

            <div class="modal-body" id="divAgregarDireccion">
                @Html.Action("AgregarDireccion", "Direccion")
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" onclick="@("window.location.href='" + @Url.Action("Informacion", "Cuenta") + "'");">Cerrar</button>
            </div>

        </div>

    </div>
</div>

<div class="modal fade" id="modalModificarDireccion" role="dialog">

    <div class="modal-dialog modal-lg">

        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Modificar dirección</h4>
            </div>

            <div class="modal-body">
                <div id="divModificarDireccion">

                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" onclick="@("window.location.href='" + @Url.Action("Informacion", "Cuenta") + "'");">Cerrar</button>
            </div>

        </div>

    </div>
</div>

<div class="modal fade" id="modalMapaParcial" role="dialog">

    <div class="modal-dialog">

        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Mapa</h4>
            </div>

            <div class="modal-body">
                <div id="divMapaParcial">

                </div>
            </div>

        </div>

    </div>
</div>

@if (Model.Count > 0)
{
    <table class="table table-hover">
        <tr>
            <th>
                Direccion
            </th>
            <th>
                Acciones
            </th>
        </tr>
        @foreach (Direccion d in Model)
        {
            <tr>
                <td>
                    @d.getString()
                </td>
                <td>
                    <a data-toggle="modal" href="#modalEliminarDireccion@(d.idDireccion)">Eliminar</a>
                    &nbsp;|&nbsp;
                    @Ajax.ActionLink("Modificar", "ModificarDireccion", "Direccion", new { idDireccion = d.idDireccion }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divModificarDireccion", HttpMethod = "GET" }, new { onclick= "mostrarModalModificarDireccion()" })
                    &nbsp;|&nbsp;
                    @Ajax.ActionLink("Mostrar mapa", "MapaParcial", "Pruebas", new { lat = d.latitud, lng = d.longitud }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divMapaParcial" }, new { onclick = "mostrarModalMapaParcial()" })
                </td>
            </tr>

            <div class="modal fade" id="modalEliminarDireccion@(d.idDireccion)" role="dialog">

                <div class="modal-dialog">

                    <div class="modal-content">

                        <div class="modal-header">
                            <h4 class="modal-title">Eliminar direccion</h4>
                        </div>

                        <div class="modal-body" id="divEliminarDireccion@(d.idDireccion)">
                            <div class="alert alert-warning">Está seguro que quiere eliminar la dirección "@d.getString()"</div>
                            <div class="btn-group btn-group-justified">
                                @Ajax.ActionLink("Sí", "EliminarDireccion", "Direccion", new { idDireccion = d.idDireccion }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = ("divEliminarDireccion" + d.idDireccion) }, new { @class = "btn btn-danger" })
                                <a class="btn btn-default" data-dismiss="modal">Cancelar</a>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        }
    </table>
}
else
{
    <div class="alert alert-info">Sin direcciones</div>
}

Views/Direccion/ModificarDireccion.cshtml
@using _2017_05_24ULSAVentas.Models
@model Direccion

@{
    bool? direccionDireccionModificada = (bool?)TempData["direccionDireccionModificada"];
}

@if (direccionDireccionModificada == true)
{
    <div class="alert alert-success">
        Dirección modificada con éxito.
    </div>
}
else if (direccionDireccionModificada == false)
{
    <div class="alert alert-danger">
        No se ha modificado la dirección.
    </div>
}

@using (Ajax.BeginForm("ModificarDireccion", "Direccion", new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "divModificarDireccion", HttpMethod = "POST" }))
{
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(d => d.idDireccion)

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(d => d.calle)
                @Html.TextBoxFor(d => d.calle, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.numeroExterior) (Opcional)
                @Html.TextBoxFor(d => d.numeroExterior, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(d => d.numeroInterior) (Opcional)
                @Html.TextBoxFor(d => d.numeroInterior, new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(d => d.colonia)
                @Html.TextBoxFor(d => d.colonia, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.codigoPostal)
                @Html.TextBoxFor(d => d.codigoPostal, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.estado)
                @Html.TextBoxFor(d => d.estado, new { @class = "form-control" })
            </div>
        </div>

        <div class="col-md-12">
            <h4 class="page-header"><span class="glyphicon glyphicon-map-marker"></span> Opciones de mapa (opcionales)</h4>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(d => d.latitud)
                @Html.TextBoxFor(d => d.latitud, new { @class = "form-control" })
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(d => d.longitud)
                @Html.TextBoxFor(d => d.longitud, new { @class = "form-control" })
            </div>
        </div>

        <div class="col-md-4 col-md-offset-4">
            <input type="submit" class="btn btn-success btn-block" value="Actualizar" />
        </div>
    </div>
}

@{
    TempData["direccionDireccionModificada"] = null;
}